set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(TOOLCHAIN_NAME aarch64-none-linux-gnu)

set(TOOLCHAIN_HOME ${CMAKE_CURRENT_LIST_DIR}/.. )
set(TOOLCHAIN_INCLUDE	${TOOLCHAIN_HOME}/${TOOLCHAIN_NAME}/include 
						${TOOLCHAIN_HOME}/${TOOLCHAIN_NAME}/libc/usr/include )
set(TOOLCHAIN_LIB	${TOOLCHAIN_HOME}/${TOOLCHAIN_NAME}/lib 
					${TOOLCHAIN_HOME}/${TOOLCHAIN_NAME}/libc/usr/lib )

set(CMAKE_C_COMPILER ${TOOLCHAIN_HOME}/bin/${TOOLCHAIN_NAME}-gcc${EXEC_SUFFIX} )
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_HOME}/bin/${TOOLCHAIN_NAME}-g++${EXEC_SUFFIX} )
set(CMAKE_ASM_COMPILER ${TOOLCHAIN_HOME}/bin/${TOOLCHAIN_NAME}-as${EXEC_SUFFIX} )
set(CMAKE_LINKER ${TOOLCHAIN_HOME}/bin/${TOOLCHAIN_NAME}-ld${EXEC_SUFFIX} )
set(CMAKE_STRIP ${TOOLCHAIN_HOME}/bin/${TOOLCHAIN_NAME}-strip${EXEC_SUFFIX} )

set(CMAKE_INCLUDE_PATH ${TOOLCHAIN_INCLUDE})
set(CMAKE_LIBRARY_PATH ${TOOLCHAIN_LIB})

set(CMAKE_FIND_ROOT_PATH ${TOOLCHAIN_HOME}/${TOOLCHAIN_NAME} )
set(CMAKE_FIND_ROOT_MODE_PROGRAM NEVER )
set(CMAKE_FIND_ROOT_MODE_LIBRARY ONLY )
set(CMAKE_FIND_ROOT_MODE_INCLUDE ONLY )
set(CMAKE_FIND_ROOT_MODE_PACKAGE ONLY )
